#pragma once

#include <stdint.h>

// clang-format off

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.6.0
// Descriptor size: 31 (bytes)
// +----------+-------+-------------------+
// | ReportId | Kind  | ReportSizeInBytes |
// +----------+-------+-------------------+
// |        1 | Input |                 7 |
// +----------+-------+-------------------+
static const uint8_t orchid_buttons_board_hid_report_descriptor[] =
{
    0x05, 0x01,    // UsagePage(Generic Desktop[0x0001])
    0x09, 0x05,    // UsageId(Gamepad[0x0005])
    0xA1, 0x01,    // Collection(Application)
    0x85, 0x01,    //     ReportId(1)
    0x05, 0x09,    //     UsagePage(Button[0x0009])
    0x19, 0x01,    //     UsageIdMin(Button 1[0x0001])
    0x29, 0x31,    //     UsageIdMax(Button 49[0x0031])
    0x15, 0x00,    //     LogicalMinimum(0)
    0x25, 0x01,    //     LogicalMaximum(1)
    0x95, 0x31,    //     ReportCount(49)
    0x75, 0x01,    //     ReportSize(1)
    0x81, 0x02,    //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x95, 0x01,    //     ReportCount(1)
    0x75, 0x07,    //     ReportSize(7)
    0x81, 0x03,    //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,          // EndCollection()
};

// clang-format on

#pragma pack(push, 1)

#define ORCHID_BUTTONS_BOARD_HID_REPORT_DESCRIPTOR_ID (1)
typedef struct orchid_buttons_board_hid_report {
  uint8_t report_id;  // ORCHID_BUTTONS_BOARD_HID_REPORT_DESCRIPTOR_ID
  uint8_t payload[7];
} orchid_buttons_board_hid_report_t;

#pragma pack(pop)

