#pragma once

#include <stdint.h>

// clang-format off

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.6.0
// Descriptor size: 84 (bytes)
// +----------+-------+-------------------+
// | ReportId | Kind  | ReportSizeInBytes |
// +----------+-------+-------------------+
// |        1 | Input |                 9 |
// +----------+-------+-------------------+
static const uint8_t orchid_dualshock4_hid_report_descriptor[] =
{
    0x05, 0x01,          // UsagePage(Generic Desktop[0x0001])
    0x09, 0x05,          // UsageId(Gamepad[0x0005])
    0xA1, 0x01,          // Collection(Application)
    0x85, 0x01,          //     ReportId(1)
    0x09, 0x30,          //     UsageId(X[0x0030])
    0x09, 0x31,          //     UsageId(Y[0x0031])
    0x09, 0x32,          //     UsageId(Z[0x0032])
    0x09, 0x35,          //     UsageId(Rz[0x0035])
    0x15, 0x00,          //     LogicalMinimum(0)
    0x26, 0xFF, 0x00,    //     LogicalMaximum(255)
    0x95, 0x04,          //     ReportCount(4)
    0x75, 0x08,          //     ReportSize(8)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0x39,          //     UsageId(Hat Switch[0x0039])
    0x46, 0x3B, 0x01,    //     PhysicalMaximum(315)
    0x65, 0x14,          //     Unit('degrees', EnglishRotation, Degrees:1)
    0x25, 0x07,          //     LogicalMaximum(7)
    0x95, 0x01,          //     ReportCount(1)
    0x75, 0x03,          //     ReportSize(3)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x75, 0x01,          //     ReportSize(1)
    0x81, 0x03,          //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x09,          //     UsagePage(Button[0x0009])
    0x19, 0x01,          //     UsageIdMin(Button 1[0x0001])
    0x29, 0x0E,          //     UsageIdMax(Button 14[0x000E])
    0x45, 0x00,          //     PhysicalMaximum(0)
    0x65, 0x00,          //     Unit(None)
    0x25, 0x01,          //     LogicalMaximum(1)
    0x95, 0x0E,          //     ReportCount(14)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x95, 0x01,          //     ReportCount(1)
    0x75, 0x06,          //     ReportSize(6)
    0x81, 0x03,          //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x01,          //     UsagePage(Generic Desktop[0x0001])
    0x09, 0x33,          //     UsageId(Rx[0x0033])
    0x09, 0x34,          //     UsageId(Ry[0x0034])
    0x26, 0xFF, 0x00,    //     LogicalMaximum(255)
    0x95, 0x02,          //     ReportCount(2)
    0x75, 0x08,          //     ReportSize(8)
    0x81, 0x02,          //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                // EndCollection()
};

// clang-format on

#pragma pack(push, 1)

#define ORCHID_DUALSHOCK4_HID_REPORT_DESCRIPTOR_ID (1)
typedef struct orchid_dualshock4_hid_report {
  uint8_t report_id;  // ORCHID_DUALSHOCK4_HID_REPORT_DESCRIPTOR_ID
  union {
    uint8_t payload[9];
    struct {
      uint8_t left_stick_x;   // -127 to +127
      uint8_t left_stick_y;   // -127 to +127
      uint8_t right_stick_x;  // -127 to +127
      uint8_t right_stick_y;  // -127 to +127
      uint8_t dpad : 3;       // 0 to 7, representing 45 deg increments
      uint8_t : 1;
      uint8_t button1 : 1;
      uint8_t button2 : 1;
      uint8_t button3 : 1;
      uint8_t button4 : 1;
      uint8_t button5 : 1;
      uint8_t button6 : 1;
      uint8_t button7 : 1;
      uint8_t button8 : 1;
      uint8_t button9 : 1;
      uint8_t button10 : 1;
      uint8_t button11 : 1;
      uint8_t button12 : 1;
      uint8_t button13 : 1;
      uint8_t button14 : 1;
      uint8_t : 6;
      uint8_t left_trigger;   // -127 to +127
      uint8_t right_trigger;  // -127 to +127
    };
  };
} orchid_dualshock4_hid_report_t;

#pragma pack(pop)

