#pragma once

#include <stdint.h>

// clang-format off

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.6.0
// Descriptor size: 52 (bytes)
// +----------+-------+-------------------+
// | ReportId | Kind  | ReportSizeInBytes |
// +----------+-------+-------------------+
// |        1 | Input |                 4 |
// +----------+-------+-------------------+
static const uint8_t orchid_mouse_keyboard_hid_report_descriptor[] =
{
    0x05, 0x01,    // UsagePage(Generic Desktop[0x0001])
    0x09, 0x02,    // UsageId(Mouse[0x0002])
    0xA1, 0x01,    // Collection(Application)
    0x85, 0x01,    //     ReportId(1)
    0x09, 0x01,    //     UsageId(Pointer[0x0001])
    0xA1, 0x00,    //     Collection(Physical)
    0x09, 0x30,    //         UsageId(X[0x0030])
    0x09, 0x31,    //         UsageId(Y[0x0031])
    0x09, 0x38,    //         UsageId(Wheel[0x0038])
    0x15, 0x80,    //         LogicalMinimum(-128)
    0x25, 0x7F,    //         LogicalMaximum(127)
    0x95, 0x03,    //         ReportCount(3)
    0x75, 0x08,    //         ReportSize(8)
    0x81, 0x06,    //         Input(Data, Variable, Relative, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x09,    //         UsagePage(Button[0x0009])
    0x19, 0x01,    //         UsageIdMin(Button 1[0x0001])
    0x29, 0x02,    //         UsageIdMax(Button 2[0x0002])
    0x15, 0x00,    //         LogicalMinimum(0)
    0x25, 0x01,    //         LogicalMaximum(1)
    0x95, 0x02,    //         ReportCount(2)
    0x75, 0x01,    //         ReportSize(1)
    0x81, 0x02,    //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,          //     EndCollection()
    0x95, 0x01,    //     ReportCount(1)
    0x75, 0x06,    //     ReportSize(6)
    0x81, 0x03,    //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,          // EndCollection()
};

// clang-format on

static const uint8_t orchid_mouse_hid_report_descriptor_id = 1;

// input 1
typedef struct orchid_mouse_hid_report {
  uint8_t report_id;
  union {
    uint8_t payload[4];
    struct {
      uint8_t dx;
      uint8_t dy;
      uint8_t wheel;
      uint8_t buttons;
    };
  };
} orchid_mouse_hid_report_t;

static const uint8_t orchid_keyboard_hid_report_descriptor_id = 2;

// input 2
typedef struct orchid_keyboard_hid_report {
  uint8_t reportID;
  // TODO: payload
} orchid_keyboard_hid_report_t;

