#pragma once

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.6.0
// Descriptor size: 91 (bytes)
// +----------+-------+-------------------+
// | ReportId | Kind  | ReportSizeInBytes |
// +----------+-------+-------------------+
// |        1 | Input |                 4 |
// +----------+-------+-------------------+
// |        2 | Input |                87 |
// +----------+-------+-------------------+
static const uint8_t hidReportDescriptor[] = 
{
    0x05, 0x01,    // UsagePage(Generic Desktop[0x0001])
    0x09, 0x02,    // UsageId(Mouse[0x0002])
    0xA1, 0x01,    // Collection(Application)
    0x85, 0x01,    //     ReportId(1)
    0x09, 0x01,    //     UsageId(Pointer[0x0001])
    0xA1, 0x00,    //     Collection(Physical)
    0x09, 0x30,    //         UsageId(X[0x0030])
    0x09, 0x31,    //         UsageId(Y[0x0031])
    0x09, 0x38,    //         UsageId(Wheel[0x0038])
    0x15, 0x80,    //         LogicalMinimum(-128)
    0x25, 0x7F,    //         LogicalMaximum(127)
    0x95, 0x03,    //         ReportCount(3)
    0x75, 0x08,    //         ReportSize(8)
    0x81, 0x06,    //         Input(Data, Variable, Relative, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x09,    //         UsagePage(Button[0x0009])
    0x19, 0x01,    //         UsageIdMin(Button 1[0x0001])
    0x29, 0x02,    //         UsageIdMax(Button 2[0x0002])
    0x15, 0x00,    //         LogicalMinimum(0)
    0x25, 0x01,    //         LogicalMaximum(1)
    0x95, 0x02,    //         ReportCount(2)
    0x75, 0x01,    //         ReportSize(1)
    0x81, 0x02,    //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,          //     EndCollection()
    0x95, 0x01,    //     ReportCount(1)
    0x75, 0x06,    //     ReportSize(6)
    0x81, 0x03,    //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,          // EndCollection()
    0x05, 0x01,    // UsagePage(Generic Desktop[0x0001])
    0x09, 0x06,    // UsageId(Keyboard[0x0006])
    0xA1, 0x01,    // Collection(Application)
    0x85, 0x02,    //     ReportId(2)
    0x05, 0x07,    //     UsagePage(Keyboard/Keypad[0x0007])
    0x19, 0xE0,    //     UsageIdMin(Keyboard LeftControl[0x00E0])
    0x29, 0xE7,    //     UsageIdMax(Keyboard Right GUI[0x00E7])
    0x95, 0x08,    //     ReportCount(8)
    0x75, 0x01,    //     ReportSize(1)
    0x81, 0x02,    //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x19, 0x04,    //     UsageIdMin(Keyboard A[0x0004])
    0x29, 0x65,    //     UsageIdMax(Keyboard Application[0x0065])
    0x25, 0x65,    //     LogicalMaximum(101)
    0x95, 0x62,    //     ReportCount(98)
    0x75, 0x07,    //     ReportSize(7)
    0x81, 0x02,    //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x95, 0x01,    //     ReportCount(1)
    0x75, 0x02,    //     ReportSize(2)
    0x81, 0x03,    //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,          // EndCollection()
};

#pragma pack(push,1)

#define ORCHID_MOUSE_HID_REPORT_DESCRIPTOR_ID (1)
typedef struct orchid_mouse_hid_report
{
    uint8_t report_id; // ORCHID_MOUSE_HID_REPORT_DESCRIPTOR_ID
    union {
      uint8_t payload[4];
      struct {
        uint8_t dx;
        uint8_t dy;
        uint8_t wheel;
        uint8_t buttons;
      };
    };
} orchid_mouse_hid_report;

#define ORCHID_KEYBOARD_HID_REPORT_DESCRIPTOR_ID (2)
typedef struct orchid_keyboard_hid_report
{
    uint8_t report_id; // ORCHID_KEYBOARD_HID_REPORT_DESCRIPTOR_ID;
    uint8_t payload[87];
} orchid_keyboard_hid_report_t;

#pragma pack(pop)

// clang-format on
