#pragma once

#include <stdint.h>

// clang-format off

// AUTO-GENERATED by WaratahCmd.exe (https://github.com/microsoft/hidtools)

// HID Usage Tables: 1.6.0
// Descriptor size: 118 (bytes)
// +----------+-------+-------------------+
// | ReportId | Kind  | ReportSizeInBytes |
// +----------+-------+-------------------+
// |        1 | Input |                16 |
// +----------+-------+-------------------+
static const uint8_t orchid_xboxone_model_1708_hid_report_descriptor[] =
{
    0x05, 0x01,                      // UsagePage(Generic Desktop[0x0001])
    0x09, 0x05,                      // UsageId(Gamepad[0x0005])
    0xA1, 0x01,                      // Collection(Application)
    0x85, 0x01,                      //     ReportId(1)
    0x09, 0x01,                      //     UsageId(Pointer[0x0001])
    0xA1, 0x00,                      //     Collection(Physical)
    0x09, 0x30,                      //         UsageId(X[0x0030])
    0x09, 0x31,                      //         UsageId(Y[0x0031])
    0x15, 0x00,                      //         LogicalMinimum(0)
    0x27, 0xFF, 0xFF, 0x00, 0x00,    //         LogicalMaximum(65,535)
    0x95, 0x02,                      //         ReportCount(2)
    0x75, 0x10,                      //         ReportSize(16)
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                            //     EndCollection()
    0x09, 0x01,                      //     UsageId(Pointer[0x0001])
    0xA1, 0x00,                      //     Collection(Physical)
    0x09, 0x32,                      //         UsageId(Z[0x0032])
    0x09, 0x35,                      //         UsageId(Rz[0x0035])
    0x81, 0x02,                      //         Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                            //     EndCollection()
    0x05, 0x02,                      //     UsagePage(Simulation Controls[0x0002])
    0x09, 0xC5,                      //     UsageId(Brake[0x00C5])
    0x26, 0xFF, 0x03,                //     LogicalMaximum(1,023)
    0x95, 0x01,                      //     ReportCount(1)
    0x75, 0x0A,                      //     ReportSize(10)
    0x81, 0x02,                      //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x75, 0x06,                      //     ReportSize(6)
    0x81, 0x03,                      //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x09, 0xC4,                      //     UsageId(Accelerator[0x00C4])
    0x75, 0x0A,                      //     ReportSize(10)
    0x81, 0x02,                      //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x75, 0x06,                      //     ReportSize(6)
    0x81, 0x03,                      //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x01,                      //     UsagePage(Generic Desktop[0x0001])
    0x09, 0x39,                      //     UsageId(Hat Switch[0x0039])
    0x46, 0x3B, 0x01,                //     PhysicalMaximum(315)
    0x65, 0x14,                      //     Unit('degrees', EnglishRotation, Degrees:1)
    0x25, 0x08,                      //     LogicalMaximum(8)
    0x75, 0x04,                      //     ReportSize(4)
    0x81, 0x02,                      //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x81, 0x03,                      //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x09,                      //     UsagePage(Button[0x0009])
    0x19, 0x01,                      //     UsageIdMin(Button 1[0x0001])
    0x29, 0x0F,                      //     UsageIdMax(Button 15[0x000F])
    0x45, 0x00,                      //     PhysicalMaximum(0)
    0x65, 0x00,                      //     Unit(None)
    0x25, 0x01,                      //     LogicalMaximum(1)
    0x95, 0x0F,                      //     ReportCount(15)
    0x75, 0x01,                      //     ReportSize(1)
    0x81, 0x02,                      //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x95, 0x01,                      //     ReportCount(1)
    0x81, 0x03,                      //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x05, 0x0C,                      //     UsagePage(Consumer[0x000C])
    0x09, 0xB2,                      //     UsageId(Record[0x00B2])
    0x81, 0x02,                      //     Input(Data, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0x75, 0x07,                      //     ReportSize(7)
    0x81, 0x03,                      //     Input(Constant, Variable, Absolute, NoWrap, Linear, PreferredState, NoNullPosition, BitField)
    0xC0,                            // EndCollection()
};

// clang-format on

#pragma pack(push, 1)

#define ORCHID_XBOXONE_MODEL_1708_HID_REPORT_DESCRIPTOR_ID (1)
typedef struct orchid_xboxone_model_1708_hid_report {
  uint8_t report_id;  // ORCHID_XBOXONE_MODEL_1708_HID_REPORT_DESCRIPTOR_ID
  union {
    uint8_t payload[16];
    struct {
      uint16_t left_stick_x;       // -32767 to +32767
      uint16_t left_stick_y;       // -32767 to +32767
      uint16_t right_stick_x;      // -32767 to +32767
      uint16_t right_stick_y;      // -32767 to +32767
      uint16_t left_trigger : 10;  // 0 to 1023
      uint8_t : 6;
      uint16_t right_trigger : 10;  // 0 to 1023
      uint8_t : 6;
      uint8_t dpad : 4;  // 0 to 7, representing 45 deg increments
      uint8_t : 4;
      uint8_t button1 : 1;
      uint8_t button2 : 1;
      uint8_t button3 : 1;
      uint8_t button4 : 1;
      uint8_t button5 : 1;
      uint8_t button6 : 1;
      uint8_t button7 : 1;
      uint8_t button8 : 1;
      uint8_t button9 : 1;
      uint8_t button10 : 1;
      uint8_t button11 : 1;
      uint8_t button12 : 1;
      uint8_t button13 : 1;
      uint8_t button14 : 1;
      uint8_t button15 : 1;
      uint8_t : 1;
      uint8_t record : 1;
      uint8_t : 7;
    };
  };
} orchid_xboxone_model_1708_hid_report_t;

#pragma pack(pop)

